<?php

namespace TomatoPHP\FilamentPlugins\Console\Contracts;

use Illuminate\Support\Collection;
use TomatoPHP\FilamentPlugins\Console\Contracts\Plugin;

class PluginsList
{
    public static function make(): Collection
    {
        return collect([
            Plugin::make('filament-users')
                ->group('User Management')
                ->label('User Manager')
                ->module('FilamentUsers')
                ->description('User Table Resource with a lot of package integrations')
                ->url('https://www.github.com/tomatophp/filament-users')
                ->instractions('->plugin(\TomatoPHP\FilamentUsers\FilamentUsersPlugin::make())')
                ->command('tomatophp/filament-users'),
            Plugin::make('filament-translations')
                ->group('Developer Tools')
                ->module('FilamentTranslations')
                ->label('Translations Manager')
                ->description('Manage your translation with DB and cache, you can scan your language tags like trans(), __(), and get the string inside and translate them using UI.')
                ->url('https://www.github.com/tomatophp/filament-translations')
                ->instractions('->plugin(\TomatoPHP\FilamentTranslations\FilamentTranslationsPlugin::make())')
                ->command('tomatophp/filament-translations'),
            Plugin::make('filament-translation-component')
                ->group('Developer Tools')
                ->label('Translation Component')
                ->description('Translation Component as a key/value to use it with Spatie Translatable FilamentPHP Plugin')
                ->url('https://www.github.com/tomatophp/filament-translation-component')
                ->command('tomatophp/filament-translation-component'),
            Plugin::make('filament-developer-gate')
                ->group('Developer Tools')
                ->module('FilamentDeveloperGate')
                ->label('Developer Gate')
                ->description('Secure your selected route by using a middleware with a static password for developers only')
                ->url('https://www.github.com/tomatophp/filament-developer-gate')
                ->instractions('->plugin(\TomatoPHP\FilamentDeveloperGate\FilamentDeveloperGatePlugin::make())')
                ->command('tomatophp/filament-developer-gate'),
            Plugin::make('filament-accounts')
                ->group('User Management')
                ->module('FilamentAccounts')
                ->label('Accounts Builder')
                ->description('full accounts manager with API/Notifications/Contacts to manage your contacts and accounts')
                ->url('https://www.github.com/tomatophp/filament-accounts')
                ->instractions('->plugin(\TomatoPHP\FilamentAccounts\FilamentAccountsPlugin::make())')
                ->command('tomatophp/filament-accounts'),
            Plugin::make('filament-wallet')
                ->group('Payments')
                ->module('FilamentWallet')
                ->label('Wallets Manager')
                ->description('Account Balance / Wallets Manager For FilamentPHP and Filament Account Builder')
                ->url('https://www.github.com/tomatophp/filament-wallet')
                ->instractions('->plugin(\TomatoPHP\FilamentWallet\FilamentWalletPlugin::make())')
                ->command('tomatophp/filament-wallet'),
            Plugin::make('filament-withdrawals')
                ->group('Payments')
                ->module('FilamentWithdrawals')
                ->label('Wallets Withdrawals')
                ->description('Manage your withdrawals in Filament')
                ->url('https://www.github.com/tomatophp/filament-withdrawals')
                ->instractions('->plugin(\TomatoPHP\FilamentWithdrawals\FilamentWithdrawalsPlugin::make())')
                ->command('tomatophp/filament-withdrawals'),
            Plugin::make('filament-alerts')
                ->group('Notifications')
                ->module('FilamentAlerts')
                ->label('Alerts Sender')
                ->description('Send notifications to users using notification templates and multi-notification channels')
                ->url('https://www.github.com/tomatophp/filament-alerts')
                ->instractions('->plugin(\TomatoPHP\FilamentAlerts\FilamentAlertsPlugin::make())')
                ->command('tomatophp/filament-alerts'),
            Plugin::make('filament-fcm')
                ->group('Notifications')
                ->label('FCM Integration')
                ->description('Firebase Cloud Messaging integration to Native FilamentPHP Notification Package')
                ->url('https://www.github.com/tomatophp/filament-fcm')
                ->instractions('->plugin(\TomatoPHP\FilamentFcm\FilamentFcmPlugin::make())')
                ->command('tomatophp/filament-fcm'),
            Plugin::make('filament-twilio')
                ->group('Notifications')
                ->label('Twilio Integration')
                ->description('Send Whatsapp messages using Twilio and native filament Notification Facade class')
                ->url('https://www.github.com/tomatophp/filament-twilio')
                ->command('tomatophp/filament-twilio'),
            Plugin::make('filament-discord')
                ->group('Notifications')
                ->label('Discord Integration')
                ->description('Send Notification to discord channel Webhook using native FilamentPHP Notification Facade class')
                ->url('https://www.github.com/tomatophp/filament-discord')
                ->command('tomatophp/filament-discord'),
            Plugin::make('filament-helpers')
                ->group('Developer Tools')
                ->label('Helper Classes')
                ->description('Helper Class Generator to manage your forms and table inside your filament app')
                ->url('https://www.github.com/tomatophp/filament-helpers')
                ->command('tomatophp/filament-helpers'),
            Plugin::make('filament-types')
                ->group('Developer Tools')
                ->module('FilamentTypes')
                ->label('Types Manager')
                ->description('Manage any type on your app in the Database with easy Resources for FilamentPHP')
                ->instractions('->plugin(\TomatoPHP\FilamentTypes\FilamentTypesPlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-types')
                ->command('tomatophp/filament-types'),
            Plugin::make('filament-menus')
                ->group('Developer Tools')
                ->module('FilamentMenus')
                ->label('Menu Generator')
                ->description('Menu Database builder to use as a navigation on Filament Panel or as a Livewire Component')
                ->instractions('->plugin(\TomatoPHP\FilamentMenus\FilamentMenusPlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-menus')
                ->command('tomatophp/filament-menus'),
            Plugin::make('filament-icons')
                ->group('Developer Tools')
                ->module('FilamentIcons')
                ->label('Icons Picker')
                ->description('Picker & Table Column & Icons Provider for FilamentPHP')
                ->url('https://www.github.com/tomatophp/filament-icons')
                ->command('tomatophp/filament-icons'),
            Plugin::make('filament-cms')
                ->group('Content Manager')
                ->module('FilamentCMS')
                ->label('CMS Builder')
                ->description('Full CMS System with easy-to-use page builder & theme manager for FilamentPHP')
                ->instractions('->plugin(\TomatoPHP\FilamentCMS\FilamentCmsPlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-cms')
                ->command('tomatophp/filament-cms'),
            Plugin::make('filament-media-manager')
                ->group('Content Manager')
                ->module('FilamentMediaManager')
                ->label('Media Manager')
                ->description('Manage your media files using spatie media library with easy to use GUI for FilamentPHP')
                ->url('https://www.github.com/tomatophp/filament-media-manager')
                ->instractions('->plugin(\TomatoPHP\FilamentMediaManager\FilamentMediaManagerPlugin::make())')
                ->command('tomatophp/filament-media-manager'),
            Plugin::make('filament-browser')
                ->group('Developer Tools')
                ->module('FilamentBrowser')
                ->label('File Browser')
                ->description('File & Folders & Media Browser With Code Editor')
                ->instractions('->plugin(\TomatoPHP\FilamentBrowser\FilamentBrowserPlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-browser')
                ->command('tomatophp/filament-browser'),
            Plugin::make('filament-artisan')
                ->group('Developer Tools')
                ->module('FilamentArtisan')
                ->label('Artisan Command Runner')
                ->description('Simple yet powerful library for running some artisan commands. this package is a fork of artisan-gui with some custom for filament UI')
                ->instractions('->plugin(\TomatoPHP\FilamentArtisan\FilamentArtisanPlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-artisan')
                ->command('tomatophp/filament-artisan'),
            Plugin::make('filament-settings-hub')
                ->group('Developer Tools')
                ->module('FilamentSettingsHub')
                ->label('Settings Hub')
                ->description('Manage your app settings with GUI and helpers')
                ->instractions('->plugin(\TomatoPHP\FilamentSettingsHub\FilamentSettingsHubPlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-settings-hub')
                ->command('tomatophp/filament-settings-hub'),
            Plugin::make('filament-locations')
                ->group('Developer Tools')
                ->module('FilamentLocations')
                ->label('Locations Seeder')
                ->description('Database Seeds for Locations for FilamentPHP')
                ->instractions('->plugin(\TomatoPHP\FilamentLocations\FilamentLocationsPlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-locations')
                ->command('tomatophp/filament-locations'),
            Plugin::make('filament-api')
                ->group('Developer Tools')
                ->module('FilamentApi')
                ->label('Resource API Generator')
                ->description('Generate APIs from your filament resource using a single line of code')
                ->instractions('->plugin(\TomatoPHP\FilamentApi\FilamentApiPlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-api')
                ->command('tomatophp/filament-api'),
            Plugin::make('filament-ecommerce')
                ->group('E-commerce')
                ->module('FilamentEcommerce')
                ->label('E-commerce Builder')
                ->description('Build your own e-commerce store with FilamentPHP with the Power of Tomato CMS Builder')
                ->instractions('->plugin(\TomatoPHP\FilamentEcommerce\FilamentEcommercePlugin::make())')
                ->url('https://www.github.com/tomatophp/filament-ecommerce')
                ->command('tomatophp/filament-ecommerce'),
            Plugin::make('filament-pos')
                ->group('E-commerce')
                ->module('FilamentPOS')
                ->label('Point Of Sale')
                ->description('POS System for FilamentPHP with a lot of features and integration with Ecommerce Builder')
                ->url('https://www.github.com/tomatophp/filament-pos')
                ->instractions('->plugin(\TomatoPHP\FilamentPos\FilamentPOSPlugin::make())')
                ->command('tomatophp/filament-pos'),
            Plugin::make('filament-notes')
                ->group('Content Manager')
                ->label('Sticky Notes')
                ->module('FilamentNotes')
                ->description('Add Sticky Notes to your FilamentPHP dashboard with tons of options and style')
                ->url('https://www.github.com/tomatophp/filament-notes')
                ->instractions('->plugin(\TomatoPHP\FilamentNotes\FilamentNotesPlugin::make())')
                ->command('tomatophp/filament-notes'),
            Plugin::make('filament-invoices')
                ->group('Payments')
                ->label('Invoices Manager')
                ->module('FilamentInvoices')
                ->description('Generate and manage your invoices / payments using multi currencies and multi types in FilamentPHP')
                ->url('https://www.github.com/tomatophp/filament-invoices')
                ->instractions('->plugin(\TomatoPHP\FilamentInvoices\FilamentInvoicesPlugin::make())')
                ->command('tomatophp/filament-invoices'),
            Plugin::make('filament-pwa')
                ->group('Developer Tools')
                ->label('PWA Generator')
                ->description('get a PWA feature on your FilamentPHP app with settings from panel')
                ->url('https://www.github.com/tomatophp/filament-pwa')
                ->instractions('->plugin(\TomatoPHP\FilamentPWA\FilamentPWAPlugin::make())')
                ->command('tomatophp/filament-pwa'),
            Plugin::make('filament-simple-theme')
                ->group('Themes')
                ->label('Simple Theme')
                ->description('A simple theme for FilamentPHP with custom user menu in sidebar')
                ->url('https://www.github.com/tomatophp/filament-simple-theme')
                ->instractions('->plugin(\TomatoPHP\FilamentSimpleTheme\FilamentSimpleThemePlugin::make())')
                ->command('tomatophp/filament-simple-theme'),
            Plugin::make('filament-subscriptions')
                ->group('Payments')
                ->module('FilamentSubscriptions')
                ->label('Subscriptions')
                ->description('Manage subscriptions and feature access with customizable plans in FilamentPHP')
                ->url('https://www.github.com/tomatophp/filament-subscriptions')
                ->instractions('->plugin(\TomatoPHP\FilamentSubscriptions\FilamentSubscriptionsPlugin::make())')
                ->command('tomatophp/filament-subscriptions'),
            Plugin::make('filament-tenancy')
                ->group('Developer Tools')
                ->module('FilamentTenancy')
                ->label('Tenancy Multi-database')
                ->description('Tenancy multi-database integration for FilamentPHP')
                ->url('https://www.github.com/tomatophp/filament-tenancy')
                ->instractions('->plugin(\TomatoPHP\FilamentTenancy\FilamentTenancyPlugin::make())')
                ->command('tomatophp/filament-tenancy'),
            Plugin::make('filament-payments')
                ->group('Payments')
                ->module('FilamentPayments')
                ->label('Payment Manager')
                ->description('Manage your payments inside FilamentPHP app with multi payment gateway integration')
                ->url('https://www.github.com/tomatophp/filament-payments')
                ->instractions('->plugin(\TomatoPHP\FilamentPayments\FilamentPaymentsPlugin::make())')
                ->command('tomatophp/filament-payments'),
        ]);
    }
}
